[project]
name = "sample-open-weight-models-with-amazon-bedrock"
version = "0.1.0"
description = "Code samples for a hands-on workshop exploring open weight models on Amazon Bedrock"
requires-python = ">=3.11"
dependencies = [
    "aws-bedrock-token-generator>=1,<2",
    "boto3>=1.37.0,<2",  # Python SDK for AWS
    "crewai>=1.13,<2",
    "langchain>=1.0.3,<2",
    "langchain-aws>=1,<2",
    "langchain-core>=1.0.3,<2",
    "langchain-openai>=1.0.3,<2",
    "langgraph>=1.0.3,<2",
    "matplotlib>=3.9,<4",  # Comprehensive library for creating visualizations
    "openai>=2.6,<3",  # OpenAI Python SDK (for calling OpenAI-compatible APIs on Bedrock)
    "pandas>=2.3",  # Utilities for working with tabular data as "dataframes"
    "Pillow>=10.0.0",  # Image processing utilities
    "rich>=14.0.0",  # Render rich text in the console/terminal
    "sagemaker>=2.245,<3",  # High-level Python SDK for Amazon SageMaker
    "seaborn>=0.13.2"  # Statistical data visualization built on matplotlib
]

# This project is only for dependencies - not building libraries:
[tool.setuptools]
py-modules = []
packages = []
